#spring.application.name=Travel Managerment
#spring.datasource.url=jdbc:mysql://buerky79038ofcrqn8ei-mysql.services.clever-cloud.com:3306/buerky79038ofcrqn8ei?useSSL=TRUE&requireSSL=TRUE
#spring.datasource.username=uay33j3wnndfwnia
#spring.datasource.password=V7XlPGIbgA4n2RgtA0CN
## spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true


spring.application.name=Travel Managerment
spring.datasource.url=jdbc:mysql://mysql-4e11788-trongthaichu-db88.h.aivencloud.com:16552/defaultdb?useSSL=true&requireSSL=true&verifyServerCertificate=false
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_ovJNEE_F-V5dC9lE_Gj
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=helpdesktravelapp@gmail.com
spring.mail.password=aitg owrc kzva oznr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

